### ISSUE TITLE
Would it be possible create a v0.0.5 tag based of the current state of master?

### ISSUE THREAD

**Issue by timbarker** [sanketplus/go-mysql-lock#4]
Hello,

Would it be possible to create a v0.0.5 tag from the current state of master. The company I work at prefers to use tags in our module versions rather than using whatever is on master and we want to use some of the improved error handling that is in master but not in v0.0.4

Thanks

**Comment by sanketplus** [comment]
I had that in back of my mind. Pushed the tag. thanks for reminding @timbarker 🙌
